name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - heo-*
  pull_request:
jobs:
  ci:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
      - name: Check Gradle Version
        run: |
          chmod +x gradlew
          ./gradlew --version
      - name: Test
        run: |
          ./gradlew --parallel --max-workers=4 build
      - name: Create report file
        if: success()
        run: |
          sudo apt install -y graphviz
          JAR_FILE=$(ls -al ./build/libs/ | tail -1 | awk '{print $9}')
          java -jar ./build/libs/$JAR_FILE -d $(pwd) -p dev.heowc.heo.core -o ${{ github.event.pull_request.number }}.png
      - name: Plugin Test
        run: |
          ./gradlew -PlocalPlugin
      - name: Create self test report
        if: success() && github.event.pull_request.number != ''
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.event.pull_request.number }}.png
          name: interg-reports
          retention-days: 7

      - name: If failure then upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: '*/build/reports/tests'
          name: test-reports
          retention-days: 7